### ISSUE TITLE
Submit GMT to Windows Package Manager?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#3509]
Microsoft is developing a new [Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/), which provides the command `winget` for installing applications on Windows 10. Installing a package would be much easier on Windows by a single command, e.g., `winget install gmt`.

The list of packages available to `winget` is community-maintained, available at https://github.com/microsoft/winget-pkgs. It looks easy to submit a new package to it. We only need to provide a package manifest file, which is only a few lines. Here is [an example](https://github.com/microsoft/winget-pkgs/blob/master/manifests/ArtifexSoftware/GhostScript/9.52.yaml) for Ghostscript. It can also install a specific version, e.g., `winget install gmt --version 6.0.0`, as long as we provide manifest files for each version.

It looks promising and useful for Windows users.

**Comment by joa-quim** [comment]
A nice stealing story by MS
https://keivan.io/the-day-appget-died/

**Comment by PaulWessel** [comment]
It is tempting to say something nasty about MS here but I can easily imagine this is standard company policy at other places too.  Talk about douce bags.

**Comment by seisman** [comment]
I plan to submit GMT to the winget repository (https://github.com/microsoft/winget-pkgs).

Here is the GMT manifest file:
```yaml
Id: GenericMappingTools.gmt
Publisher: Generic Mapping Tools
Name: Generic Mapping Tools
AppMoniker: gmt
Version: 6.1.1
Homepage: https://www.generic-mapping-tools.org
Description:
  GMT is an open-source collection of command-line tools for manipulating
  geographic and Cartesian data sets (including filtering, trend fitting,
  gridding, projecting, etc.) and producing high-quality illustrations ranging
  from simple x–y plots via contour maps to artificially illuminated surfaces
  and 3D perspective views. It supports many map projections and transformations
  and includes supporting data such as coastlines, rivers, and political
  boundaries and optionally country polygons.
License: LGPL-3.0-or-later
LicenseUrl: https://github.com/GenericMappingTools/gmt/blob/master/LICENSE.TXT
InstallerType: nullsoft
Installers:
  - Arch: x64
    Url: https://github.com/GenericMappingTools/gmt/releases/download/6.1.1/gmt-6.1.1-win64.exe
    Sha256: fdaed402ef6534ef5f6bea1ccc7132cb7a89e9d5ab48a562fa1a055b1416b554
  - Arch: x86
    Url: https://github.com/GenericMappingTools/gmt/releases/download/6.1.1/gmt-6.1.1-win32.exe
    Sha256: bc098bc5ebe61467bc323bc053eb8135eafac505e9e64efb8c8a6c105e7f69a7
ManifestVersion: 0.1.0
```

Please see if you agree with these values:
```yaml
Id: GenericMappingTools.gmt              
Publisher: Generic Mapping Tools       # It should be the legal company name.
Name: Generic Mapping Tools             # It should be the friendly name of the application.
AppMoniker: gmt                                  # AppMoniker is the common name someone may use to search for the application.
```

As a comparison, here is an example manifest file for Microsoft Teams:
```
Id: microsoft.teams
Publisher: Microsoft Corporation
Name: Microsoft Teams
AppMoniker: teams
```
