### ISSUE TITLE
Use codecov-action for CI workflow

### ISSUE THREAD

**Issue by maxrjones** [GenericMappingTools/gmt#5736]
The current coverage uploader is [being deprecated](https://docs.codecov.com/docs/about-the-codecov-bash-uploader), so we need to update the workflow:

https://github.com/GenericMappingTools/gmt/blob/fa3f17cf6771cae066f0e6550b73124d583083ef/.github/workflows/tests.yml#L172-L174

We could use the [codecov-action](https://github.com/codecov/codecov-action), using a similar setup to PyGMT:
```
      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          file: ./coverage.xml # optional
          fail_ci_if_error: false
```
